apiVersion: v1
kind: Pod
metadata:
 name: container-env-test
spec:
  containers:
  - name: envctn
    image: centos:7
    args: ["tail", "-f", "/dev/null"]
    env:
    - name: KEY1
      valueFrom:
        configMapKeyRef:
          name: log-level-cmap
          key: LOG_LEVEL
    - name: KEY2
      valueFrom:
        configMapKeyRef:
          name: start-k8s
          key: k8s




