apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-v1-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
     color: black
  template:
    metadata:
      name: my-nginx-v1
      labels:
        color: black
    spec:
      containers:
      - name: my-first-nginx-ctn
        image: wnsgur1011/hello3
        ports:
        - containerPort: 80
          protocol: TCP

