apiVersion: v1
kind: Pod
metadata:
  name: my-first-nginx
spec:
  containers:
  - name: my-first-nginx-ctn
    image: nginx:1.10
    ports:
    - containerPort: 80
      protocol: TCP

  - name: test-ctn
    image: centos:7
    command: ["tail"]
    args: ["-f", "/dev/null"]
