apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  ports:
    - name: webport
      port: 8080
      targetPort: 80
      nodePort: 30001
  selector:
    color: black
  type: NodePort

