apiVersion: apps/v1
kind: Deployment
metadata:
  name: cactus
spec:
  selector:
    matchLabels:
      color: black
  replicas: 2
  template:
    metadata:
      labels:
        color: black
    spec:
      containers:
      - name: cactus-web
        image: wnsgur1011/hello8
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: registry-key1
---
apiVersion: v1
kind: Service
metadata:
  name: cactus-np
spec:
  ports:
    - name: cactus-node-port
      port: 8080
      targetPort: 80
      nodePort: 30001
  selector:
    color: black
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: mariadb
    type: database
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        type: database
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
          - containerPort: 3306
            name: db-port
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-password
                key: password

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mariadb
